### ISSUE TITLE
Is this still in use?

### ISSUE THREAD

**Issue by timolehto** [timolehto/geocoder#1]
Hi,
Doing some "spring" cleaning with my repos and was wondering if this is still in use? If so maybe you @sasukeranen or IWA want to take full ownership (and maybe consider updating with the original repo? ...it's like 1315 commits behind.. if not or I won't hear back I will just archive this.

**Comment by sasukeranen** [comment]
Heyy, thanks for asking :)
It's not in use anymore so archive away! Happy spring cleaning!
